name: Mi primer Workflow

on:
  push:
    branches:
      - Main
      
jobs:
  ejemplo:
    runs-on: ubunto-latest 
    env:
      PLATAFORMA: "AWS"
      REGION: "US-EAST-1"
    steps:
    - name: Mostrar Variables Cristian
      run: |
        echo "¡Hola, Github Actions!"
        echo "Región: $REGION"
    
